spring:
  config:
    activate:
      on-profile: dev
  kafka:
    enabled: true
    bootstrap-servers: kafka:29092
    topics:
      transactions-topic-in: transactions-topic-in
      transactions-topic-out: transactions-topic-out
    consumer:
      group-id: fin-analysis-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      backoff-interval-millis: 100
      backoff-max-failure-count: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      linger-ms: 10
      batch-size: 16384
      compression-type: snappy
      max-in-flight-requests: 5
      request-timeout-ms: 30000
      delivery-timeout-ms: 120000