openapi: 3.0.0
info:
  title: FeignDto Schemas
  description: Модели запросов по Feign Client
  version: 1.0.0
paths: { }
components:
  schemas:
    ScheduleTransactionResponse:
      type: object
      properties:
        amount:
          type: number
          format: double
        categoryId:
          type: string
          format: uuid
        date:
          type: string
          format: date-time
        description:
          type: string
        type:
          type: string
          enum: [ INCOME, EXPENSE ]

    TransactionsFilterRequestDto:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
          description: Уникальный идентификатор клиента
        type:
          type: string
          enum:
            - EXPENSE
            - INCOME
          description: Тип транзакции (доход/расход)
        startDate:
          type: string
          format: date
          description: Дата и время начала фильтрации
        endDate:
          type: string
          format: date
          description: Дата и время конца фильтрации
        page:
          type: integer
          default: 0
          description: Пагинация
        size:
          type: integer
          default: 10
          description: Количество транзакций в ответе