spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5430/fin_core_db
    driver-class-name: org.postgresql.Driver
    username: dev_user
    password: dev_password
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect